#!/bin/sh
files=$(git diff-index --name-only HEAD | grep -P '\.js$')
for file in $files; do
	error=$(esvalidate $file)
  if [ $? -eq 1 ]; then
		echo "\nCould not complete commit due to syntax error:\n"
		echo "\t$error\n"
		echo "Located in file:\n"
    echo "\t$file\n"
    exit 1
  fi
done
